name: Send Scheduled Email

on:
  schedule:
    - cron: "0 14 * * 1,3,5" # Runs every Monday, Wednesday, Friday
  workflow_dispatch:      # Allow manual triggering too

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip list  # Verify installed packages

    - name: Run email script
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        HOST: ${{ secrets.HOST }}
        RECIPIENT: ${{ secrets.RECIPIENT}}
        SMTP_PORT: ${{ secrets.SMTP_PORT}}
        MY_EMAIL: ${{ secrets.MY_EMAIL}}
      run: python main.py
